#include "../spw.hpp"

int main() {
  spw::create(spw::Info, "Info Title", "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Quisque hendrerit fringilla diam, eget mollis enim faucibus in.Praesent convallis elementum quam sed elementum.Nunc lobortis, nisi vel suscipit pulvinar, sapien lectus lobortis nibh, et rutrum magna mi quis metus.Maecenas at condimentum felis.Pellentesque nunc quam, tempus varius elementum id, viverra nec leo.Mauris consectetur sem et ligula vestibulum molestie.Curabitur consequat urna non neque rhoncus pharetra.Vivamus at orci sit amet diam commodo sollicitudin ac vel lacus.Proin vehicula, eros quis lacinia facilisis, nisi turpis maximus sapien, id commodo ante leo nec dui.Nunc fringilla sapien lacus, eu rutrum ex lacinia eget.Etiam vitae elit sagittis, pulvinar urna eget, volutpat nibh.Aenean efficitur libero quis venenatis commodo.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Suspendisse sodales sodales tincidunt.Suspendisse scelerisque ultricies ornare.Proin vitae felis non risus ornare vestibulum non id elit."
   "Donec tortor felis, molestie nec urna at, luctus ultrices quam.Etiam felis lacus, sagittis sit amet ultrices eu, egestas quis mauris.Phasellus porta tortor sed eros molestie, eget tincidunt quam feugiat.Fusce faucibus et ligula nec feugiat.Sed venenatis sollicitudin augue, non tempor augue tincidunt sed.Sed molestie tortor id diam aliquet, vel consequat odio fermentum.Nunc quis nibh sed sem sagittis sollicitudin eu vel elit.Curabitur blandit nulla et molestie interdum.Praesent eu efficitur ligula."
   "Sed quis arcu condimentum, elementum neque vel, euismod erat.Quisque tincidunt, velit elementum vestibulum imperdiet, quam elit rutrum lacus, eu auctor ipsum quam eu dolor.Fusce non nisl malesuada, viverra erat nec, ullamcorper neque.Fusce vehicula quis purus non sagittis.Vivamus viverra justo in nisi viverra, sed tincidunt risus tristique.Integer feugiat sem augue, eu sagittis lorem tristique id.Pellentesque vulputate orci et ipsum varius ornare.Fusce nulla libero, feugiat id pharetra vel, varius at tellus.Vivamus hendrerit purus sed urna egestas, id auctor nulla lacinia.Curabitur a urna quam.Praesent facilisis eros mattis, imperdiet nunc sed, feugiat lectus.Quisque posuere et turpis sed ornare."
   "Cras pretium diam sit amet massa suscipit faucibus.Sed eu risus orci.Nam enim erat, scelerisque eget feugiat ut, condimentum sed lectus.Quisque venenatis lacinia elit, ac congue enim tempus eget.Integer eleifend eros orci, iaculis consequat ipsum egestas vitae.Praesent porta dapibus odio, sit amet fringilla purus mattis et.Quisque lobortis arcu eu orci iaculis fringilla.Proin nec nulla sit amet tortor iaculis molestie vel non metus.Ut tincidunt, enim ut varius tincidunt, purus dolor egestas ligula, eu tristique lectus ex in enim.Aenean tempus semper mi, nec semper nulla commodo ut.Morbi orci nisi, pretium sed lacus scelerisque, luctus egestas tortor."
   "Pellentesque rutrum metus mauris, quis gravida ex laoreet non.Nullam blandit auctor sapien, sit amet tincidunt sem fermentum vel.Nunc efficitur ligula et vehicula dapibus.Pellentesque vel urna non nunc rhoncus maximus.Praesent eget imperdiet libero, a gravida est.Nunc vitae aliquet lectus.Suspendisse eu ligula sodales, finibus nisi suscipit, interdum velit. ");
  return 0;
}
